# Generated by Django 2.2 on 2021-12-28 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('case_id', models.IntegerField(primary_key=True, serialize=False)),
                ('case_name', models.CharField(default=None, max_length=65536, unique=True)),
                ('case_func', models.CharField(default=None, max_length=65536, unique=True)),
                ('status_cd', models.BooleanField()),
                ('case_seq', models.CharField(default=None, max_length=256, null=True)),
                ('case_type', models.CharField(default=None, max_length=256)),
                ('case_env', models.CharField(default='general', max_length=256)),
                ('remark', models.CharField(default=None, max_length=256, null=True)),
                ('create_time', models.CharField(default='2021-12-28 05:17:41', max_length=256)),
                ('update_time', models.CharField(default='2021-12-28 05:17:41', max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='EnvManagement',
            fields=[
                ('Env_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Env_name', models.CharField(max_length=128, unique=True)),
                ('desc', models.CharField(max_length=65536, null=True)),
                ('owner', models.CharField(max_length=256, null=True)),
                ('host', models.CharField(max_length=256, null=True)),
                ('create_time', models.CharField(default='2021-12-28 05:17:41', max_length=256)),
                ('update_time', models.CharField(default='2021-12-28 05:17:41', max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='GroupManagement',
            fields=[
                ('group_id', models.IntegerField(primary_key=True, serialize=False)),
                ('group_name', models.CharField(max_length=128, unique=True)),
                ('desc', models.CharField(max_length=65536, null=True)),
                ('owner', models.CharField(max_length=256, null=True)),
                ('create_time', models.CharField(default='2021-12-28 05:17:41', max_length=256)),
                ('update_time', models.CharField(default='2021-12-28 05:17:41', max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('process_id', models.IntegerField(primary_key=True, serialize=False)),
                ('report_id', models.CharField(max_length=128)),
                ('env', models.CharField(max_length=256, null=True)),
                ('filename', models.CharField(default='None', max_length=256, null=True)),
                ('casename', models.CharField(max_length=65536)),
                ('method', models.CharField(max_length=65536)),
                ('case_tested', models.IntegerField(null=True)),
                ('err_msg', models.CharField(default=None, max_length=256, null=True)),
                ('result', models.BooleanField()),
                ('TransactionID', models.CharField(default=None, max_length=256, null=True)),
                ('desc', models.CharField(default=None, max_length=16777216, null=True)),
                ('remark', models.CharField(default=None, max_length=256, null=True)),
                ('create_time', models.CharField(default='2021-12-28 05:17:41', max_length=256)),
                ('update_time', models.CharField(default='2021-12-28 05:17:41', max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='LoginResult',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('result', models.CharField(max_length=256)),
                ('desc', models.CharField(max_length=65536, null=True)),
                ('remark', models.CharField(max_length=256, null=True)),
                ('create_time', models.CharField(default='2021-12-28 05:17:41', max_length=256)),
                ('update_time', models.CharField(default='2021-12-28 05:17:41', max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Reporter',
            fields=[
                ('report_id', models.CharField(max_length=128, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=256, unique=True)),
                ('url', models.GenericIPAddressField(protocol='ipv4', unique=True)),
                ('env_Name', models.CharField(max_length=256, null=True)),
                ('env', models.CharField(max_length=256)),
                ('host', models.CharField(max_length=256, null=True)),
                ('port', models.CharField(max_length=256)),
                ('casename', models.CharField(max_length=65536, null=True)),
                ('corenum', models.IntegerField(null=True)),
                ('err_msg', models.CharField(default=None, max_length=16777216, null=True)),
                ('remark', models.CharField(max_length=256, null=True)),
                ('desc', models.CharField(max_length=256, null=True)),
                ('create_time', models.CharField(default='2021-12-28 05:17:41', max_length=256)),
                ('update_time', models.CharField(default='2021-12-28 05:17:41', max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('step_id', models.IntegerField(primary_key=True, serialize=False)),
                ('step_seq_case_func', models.CharField(default=None, max_length=65536, unique=True)),
                ('case_name', models.CharField(default=None, max_length=65536)),
                ('case_func', models.CharField(default=None, max_length=65536)),
                ('step_seq', models.IntegerField()),
                ('action_desc', models.CharField(max_length=256)),
                ('ele_action', models.CharField(max_length=256)),
                ('loc_type', models.CharField(max_length=256, null=True)),
                ('loc_value', models.CharField(max_length=256, null=True)),
                ('action_value', models.CharField(max_length=256, null=True)),
                ('argvs', models.CharField(max_length=16777216, null=True)),
                ('assert_value', models.CharField(max_length=256, null=True)),
                ('remark', models.CharField(default=None, max_length=256, null=True)),
                ('create_time', models.CharField(default='2021-12-28 05:17:41', max_length=256)),
                ('update_time', models.CharField(default='2021-12-28 05:17:41', max_length=256)),
            ],
        ),
    ]
