# Generated by Django 2.2 on 2021-12-28 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctc_backend_manage', '0002_auto_20211228_0518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reporter',
            name='env_Name',
        ),
        migrations.RemoveField(
            model_name='reporter',
            name='port',
        ),
        migrations.AlterField(
            model_name='case',
            name='create_time',
            field=models.CharField(default='2021-12-28 08:32:41', max_length=256),
        ),
        migrations.AlterField(
            model_name='case',
            name='update_time',
            field=models.CharField(default='2021-12-28 08:32:41', max_length=256),
        ),
        migrations.AlterField(
            model_name='envmanagement',
            name='create_time',
            field=models.CharField(default='2021-12-28 08:32:41', max_length=256),
        ),
        migrations.AlterField(
            model_name='envmanagement',
            name='update_time',
            field=models.CharField(default='2021-12-28 08:32:41', max_length=256),
        ),
        migrations.AlterField(
            model_name='groupmanagement',
            name='create_time',
            field=models.CharField(default='2021-12-28 08:32:41', max_length=256),
        ),
        migrations.AlterField(
            model_name='groupmanagement',
            name='update_time',
            field=models.CharField(default='2021-12-28 08:32:41', max_length=256),
        ),
        migrations.AlterField(
            model_name='item',
            name='create_time',
            field=models.CharField(default='2021-12-28 08:32:41', max_length=256),
        ),
        migrations.AlterField(
            model_name='item',
            name='update_time',
            field=models.CharField(default='2021-12-28 08:32:41', max_length=256),
        ),
        migrations.AlterField(
            model_name='loginresult',
            name='create_time',
            field=models.CharField(default='2021-12-28 08:32:41', max_length=256),
        ),
        migrations.AlterField(
            model_name='loginresult',
            name='update_time',
            field=models.CharField(default='2021-12-28 08:32:41', max_length=256),
        ),
        migrations.AlterField(
            model_name='reporter',
            name='create_time',
            field=models.CharField(default='2021-12-28 08:32:41', max_length=256),
        ),
        migrations.AlterField(
            model_name='reporter',
            name='update_time',
            field=models.CharField(default='2021-12-28 08:32:41', max_length=256),
        ),
        migrations.AlterField(
            model_name='step',
            name='create_time',
            field=models.CharField(default='2021-12-28 08:32:41', max_length=256),
        ),
        migrations.AlterField(
            model_name='step',
            name='update_time',
            field=models.CharField(default='2021-12-28 08:32:41', max_length=256),
        ),
    ]
