import os
from django.urls import path
from django.conf.urls import url
from . import views

urlpatterns = [
    path(
        "queryCasename",
        views.query_case_name,
        name="query_case_name",
    ),
    path(
        "runTest",
        views.run_test,
        name="run_test",
    ),
    path(
        "getCaseArgvs",
        views.get_case_argvs,
        name="get_case_argvs",
    ),
    path(
        "addStepArgvs",
        views.add_step_argvs,
        name="add_step_argvs",
    ),
    path(
        "addCaseArgvs",
        views.add_case_argvs,
        name="add_case_argvs",
    ),
    path(
        "queryPresentStep",
        views.query_present_step,
        name="query_present_step",
    ),
    path(
        "queryCaseStep",
        views.query_case_step,
        name="query_case_step",
    ),
    path(
        "updateStepForMove",
        views.update_step_for_move,
        name="update_step_for_move",
    ),
    path(
        "addStepThroughInsert",
        views.add_step_through_insert,
        name="add_step_through_insert",
    ),
    path(
        "delCaseStep",
        views.del_case_step,
        name="del_case_step",
    ),
    path(
        "modifyStepArgvs",
        views.modify_step_argvs,
        name="modify_step_argvs",
    ),
    path(
        "modifyCaseArgvs",
        views.modify_case_argvs,
        name="modify_case_argvs",
    ),
    path(
        "queryReport",
        views.query_report,
        name="query_report",
    ),
    path(
        "querySummary",
        views.query_summary,
        name="query_summary",
    ),
    url(
        r"^.+(test_report_.+\.\w+)",
        views.get_report,
        name="get_report",
    ),
    path(
        "queryCaseTested",
        views.query_case_tested,
        name="query_case_tested",
    ),
    path(
        "getLoginResult",
        views.get_login_result,
        name="get_login_result",
    ),
    path(
        "initLoginResult",
        views.init_login_result,
        name="init_login_result",
    ),
    path(
        "writeMobilePcc",
        views.write_mobile_pcc,
        name="write_mobile_pcc",
    ),
    path(
        "deleteCaseAllSteps",
        views.delete_case_all_steps,
        name="delete_case_all_steps",
    ),
    path(
        "queryGroupCase",
        views.query_group_case,
        name="query_group_case",
    ),
    path(
        "queryStepAccordDesc",
        views.query_step_accord_desc,
        name="query_step_accord_desc",
    ),
    path(
        "delReport",
        views.del_report,
        name="del_report",
    ),
    path(
        "modifysteps",
        views.modify_steps,
        name="modify_steps",
    ),
    path(
        "getStepDict",
        views.get_step_dict,
        name="get_step_dict",
    ),
    path(
        "get_memory",
        views.get_memory,
        name="get_memory",
    ),
    path(
        "create_group",
        views.create_group,
        name="create_group",
    ),
    path(
        "show_groups",
        views.show_groups,
        name="show_groups",
    ),
    path(
        "show_groups_details",
        views.show_groups_details,
        name="show_groups_details",
    ),
    path(
        "mod_group_name",
        views.mod_group_name,
        name="mod_group_name",
    ),
    path(
        "del_group_name",
        views.del_group_name,
        name="del_group_name",
    ),
    path(
        "create_env",
        views.create_env,
        name="create_env",
    ),
    path(
        "show_envs",
        views.show_envs,
        name="show_envs",
    ),
    path(
        "show_envs_details",
        views.show_envs_details,
        name="show_envs_details",
    ),
    path(
        "mod_env_name",
        views.mod_env_name,
        name="mod_env_name",
    ),
    path(
        "del_env_name",
        views.del_env_name,
        name="del_env_name",
    ),
]
