# Generated by Django 2.2 on 2022-03-15 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20211228_0832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='create_time',
            field=models.CharField(default='2022-03-15 22:42:07', max_length=256),
        ),
        migrations.AlterField(
            model_name='image',
            name='update_time',
            field=models.CharField(default='2022-03-15 22:42:07', max_length=256),
        ),
        migrations.AlterField(
            model_name='register',
            name='cellphone',
            field=models.IntegerField(default=20220315224207, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='create_time',
            field=models.CharField(default='2022-03-15 22:42:07', max_length=256),
        ),
        migrations.AlterField(
            model_name='register',
            name='update_time',
            field=models.CharField(default='2022-03-15 22:42:07', max_length=256),
        ),
    ]
