# Generated by Django 2.2 on 2021-12-28 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20211228_0518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='create_time',
            field=models.CharField(default='2021-12-28 08:32:41', max_length=256),
        ),
        migrations.AlterField(
            model_name='image',
            name='update_time',
            field=models.CharField(default='2021-12-28 08:32:41', max_length=256),
        ),
        migrations.AlterField(
            model_name='register',
            name='cellphone',
            field=models.IntegerField(default=20211228083241, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='create_time',
            field=models.CharField(default='2021-12-28 08:32:41', max_length=256),
        ),
        migrations.AlterField(
            model_name='register',
            name='update_time',
            field=models.CharField(default='2021-12-28 08:32:41', max_length=256),
        ),
    ]
